export default TestData = [
  {
    avatarUri: "https://randomuser.me/api/portraits/men/75.jpg",
    status: "offline",
    message: "I'm good, thanks.",
    unread: 1,
    username: "Jane Smith",
    lastseen: "11:00 PM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/women/76.jpg",
    status: "active",
    message: "What's up?",
    unread: 0,
    username: "Emily Johnson",
    lastseen: "12:00 PM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/men/77.jpg",
    status: "active",
    message: "Not much.",
    unread: 2,
    username: "Michael Brown",
    lastseen: "1:00 PM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/women/78.jpg",
    status: "offline",
    message: "How can I help?",
    unread: 0,
    username: "Sarah Lee",
    lastseen: "2:00 PM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/men/79.jpg",
    status: "active",
    message: "I need assistance.",
    unread: 1,
    username: "William Davis",
    lastseen: "3:00 PM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/women/80.jpg",
    status: "offline",
    message: "I'll call you later.",
    unread: 0,
    username: "Olivia Martin",
    lastseen: "4:00 PM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/men/81.jpg",
    status: "active",
    message: "I'm on a call.",
    unread: 2,
    username: "Benjamin Taylor",
    lastseen: "5:00 PM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/women/82.jpg",
    status: "offline",
    message: "I'm not available.",
    unread: 0,
    username: "Ava Harris",
    lastseen: "6:00 PM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/men/83.jpg",
    status: "active",
    message: "What's new?",
    unread: 1,
    username: "Ethan Walker",
    lastseen: "7:00 PM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/women/84.jpg",
    status: "offline",
    message: "I'm out.",
    unread: 0,
    username: "Isabella White",
    lastseen: "8:00 PM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/men/85.jpg",
    status: "active",
    message: "I'm in a meeting.",
    unread: 2,
    username: "Logan Hall",
    lastseen: "9:00 PM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/women/86.jpg",
    status: "offline",
    message: "I'm unavailable.",
    unread: 0,
    username: "Sophia Patel",
    lastseen: "10:00 PM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/men/87.jpg",
    status: "active",
    message: "How can I assist?",
    unread: 1,
    username: "Alexander Brooks",
    lastseen: "11:00 PM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/women/88.jpg",
    status: "offline",
    message: "I'm not here.",
    unread: 0,
    username: "Mia Jenkins",
    lastseen: "12:00 AM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/men/89.jpg",
    status: "active",
    message: "I'm on a break.",
    unread: 2,
    username: "Gabriel Russell",
    lastseen: "1:00 AM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/women/90.jpg",
    status: "offline",
    message: "I'm out of office.",
    unread: 0,
    username: "Isabella Garcia",
    lastseen: "2:00 AM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/men/91.jpg",
    status: "active",
    message: "What do you need?",
    unread: 1,
    username: "Julian Sanchez",
    lastseen: "3:00 AM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/women/92.jpg",
    status: "offline",
    message: "I'm unavailable.",
    unread: 0,
    username: "Abigail Rodriguez",
    lastseen: "4:00 AM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/men/93.jpg",
    status: "active",
    message: "I'm in a call.",
    unread: 2,
    username: "Caleb Martin",
    lastseen: "5:00 AM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/women/94.jpg",
    status: "offline",
    message: "I'm not available.",
    unread: 0,
    username: "Emily Wilson",
    lastseen: "6:00 AM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/men/95.jpg",
    status: "active",
    message: "How can I help?",
    unread: 1,
    username: "Jaxon Brown",
    lastseen: "7:00 AM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/women/96.jpg",
    status: "offline",
    message: "I'm out.",
    unread: 0,
    username: "Hannah Davis",
    lastseen: "8:00 AM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/men/97.jpg",
    status: "active",
    message: "I'm on a meeting.",
    unread: 2,
    username: "Liam Taylor",
    lastseen: "9:00 AM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/women/98.jpg",
    status: "offline",
    message: "I'm unavailable.",
    unread: 0,
    username: "Madison Harris",
    lastseen: "10:00 AM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/men/99.jpg",
    status: "active",
    message: "What's new?",
    unread: 1,
    username: "Noah Walker",
    lastseen: "11:00 AM",
  },
  {
    avatarUri: "https://randomuser.me/api/portraits/women/12.jpg",
    status: "offline",
    message: "I'm not here.",
    unread: 0,
    username: "Sofia Patel",
    lastseen: "12:00 PM",
  },
];
